{% set name = "pdfium-binaries" %}
{% set version = "118.0.5868" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/bblanchon/{{ name }}/releases/download/chromium%2{{ version[2] }}/{{ name.split('-')[0] }}-v8-mac-arm64.tgz  # [osx and arm64]
  url: https://github.com/bblanchon/{{ name }}/releases/download/chromium%2F{{ version[2] }}/{{ name.split('-')[0] }}-v8-mac-x64.tgz  # [osx and x86_64]
  url: https://github.com/bblanchon/{{ name }}}/releases/download/chromium%2F{{ version[2] }}/{{ name.split('-')[0] }}-v8-linux-x64.tgz  # [linux and x86_64]
  url: https://github.com/bblanchon/{{ name }}/releases/download/chromium%2F{{ version[2] }}/{{ name.split('-')[0] }}-v8-linux-arm64.tgz  # [linux and aarch64]
  url: https://github.com/bblanchon/{{ name }}/releases/download/chromium%2F{{ version[2] }}/{{ name.split('-')[0] }}-v8-win-x64.tgz  # [win]

build:
  number: 0
  skip: True  # [linux and (s390x or ppc64le)]

test:
  commands:
    - test -f $PREFIX/lib/libpdfium.dylib  # [osx]
    - test -f $PREFIX/lib/libpdfium.so  # [linux]
    - if not exist "%LIBRARY_LIB%\\pdfium.dll.lib" exit 1  # [win]

about:
  home: https://github.com/bblanchon/pdfium-binaries
  summary: pre-compiled binaries of the PDFium library
  description: |
    This project hosts pre-compiled binaries of the PDFium library, an open-source library for PDF manipulation and rendering.
  license: Apache-2.0
  license-family: Apache
  license-file: LICENSE
  doc_url: https://pdfium.googlesource.com/pdfium
  dev_url: https://github.com/bblanchon/pdfium-binaries

extra:
  recipe-maintainers:
    - boldorider4
