{% set name = "pdfium-binaries" %}
{% set version = "118.0.5868" %}
{% set patch = version.split(".")[2] %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/bblanchon/{{ name }}/releases/download/chromium%2F{{ patch }}/{{ name.split('-')[0] }}-mac-arm64.tgz  # [osx and arm64]
  sha256: d9d552f7eed1a5b333e79d05b8054a76f84bf00faa9c3b0b6e87c2a8a07e74ce                                                      # [osx and arm64]
  fn: {{ name }}-{{ version }}-osx-arm64.tgz                                                                                    # [osx and arm64]
  url: https://github.com/bblanchon/{{ name }}/releases/download/chromium%2F{{ patch }}/{{ name.split('-')[0] }}-mac-x64.tgz  # [osx and x86_64]
  sha256: 071d7b89587be7ca93be5220fc54066bf2bbfb87476a4fb786b7d1b4f5f071c2                                                    # [osx and x86_64]
  fn: {{ name }}-{{ version }}-osx-64.tgz                                                                                     # [osx and x86_64]
  url: https://github.com/bblanchon/{{ name }}/releases/download/chromium%2F{{ patch }}/{{ name.split('-')[0] }}-linux-x64.tgz  # [linux and x86_64]
  sha256: 975d84dfc424fdbe4a7e87af4445daee06a4a10eb9c9bbf6f5e7c9e8b2c0ac67                                                      # [linux and x86_64]
  fn: {{ name }}-{{ version }}-linux-64.tgz                                                                                     # [linux and x86_64]
  url: https://github.com/bblanchon/{{ name }}/releases/download/chromium%2F{{ patch }}/{{ name.split('-')[0] }}-linux-arm64.tgz  # [linux and aarch64]
  sha256: 01c022a0e55c60b69f0c77f99693f2bf8c34bdb89ea7fd4fe32683f2f28e3c7b                                                        # [linux and aarch64]
  fn: {{ name }}-{{ version }}-linux-aarch64.tgz                                                                                  # [linux and aarch64]
  url: https://github.com/bblanchon/{{ name }}/releases/download/chromium%2F{{ patch }}/{{ name.split('-')[0] }}-win-x64.tgz  # [win]
  sha256: 0373000970a0195f181ec8aaa199bbf25b52cfbd1ba19726ebef5b23fbac463d                                                    # [win]
  fn: {{ name }}-{{ version }}-win-64.tgz                                                                                     # [win]

build:
  number: 1
  skip: True  # [linux and (s390x or ppc64le)]
  missing_dso_whitelist:            # [linux]
    - /lib64/libpthread.so.0        # [linux]
    - /lib64/libm.so.6              # [linux]
    - /lib64/libc.so.6              # [linux]
    - /lib/libgcc_s.so.1            # [linux]
    - /lib64/libgcc_s.so.1          # [linux]
    - /lib64/ld-linux-aarch64.so.1  # [linux and aarch64]
    - /lib64/ld-linux-x86-64.so.2   # [linux and x86_64]

{% set headers = [
    "fpdf_annot.h",
    "fpdf_attachment.h",
    "fpdf_catalog.h",
    "fpdf_dataavail.h",
    "fpdf_doc.h",
    "fpdf_edit.h",
    "fpdf_ext.h",
    "fpdf_flatten.h",
    "fpdf_formfill.h",
    "fpdf_fwlevent.h",
    "fpdf_javascript.h",
    "fpdf_ppo.h",
    "fpdf_progressive.h",
    "fpdf_save.h",
    "fpdf_searchex.h",
    "fpdf_signature.h",
    "fpdf_structtree.h",
    "fpdf_sysfontinfo.h",
    "fpdf_text.h",
    "fpdf_thumbnail.h",
    "fpdf_transformpage.h",
    "fpdfview.h"
] %}

test:
  commands:
    - test -f $PREFIX/lib/libpdfium.dylib                  # [osx]
    - test -f $PREFIX/lib/libpdfium.so                     # [linux]
    - if not exist "%LIBRARY_LIB%\\pdfium.dll.lib" exit 1  # [win]
    {% for each_header in headers %}
    - test -f "${PREFIX}/include/{{ each_header }}"        # [osx or linux]
    - if not exist "%INCLUDE%\\{{ each_header }}" exit 1   # [win]
    {% endfor %}

about:
  home: https://github.com/bblanchon/pdfium-binaries
  summary: pre-compiled binaries of the PDFium library
  description: |
    This project hosts pre-compiled binaries of the PDFium library, an open-source library for PDF manipulation and rendering.
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  doc_url: https://pdfium.googlesource.com/pdfium
  dev_url: https://github.com/bblanchon/pdfium-binaries

extra:
  recipe-maintainers:
    - boldorider4
  skip-lints:
    - missing_section
    - invalid_url
